[package]
name = "gossip_glomers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
thiserror = "1.0.63"
uuid = { version = "1.10.0", features = ["rng", "serde", "v6"] }
